import React from 'react';
import { Head, Link, useForm } from '@inertiajs/react';
import AppLayout from '@/components/AppLayout';
import { ArrowLeft } from 'lucide-react';
interface Task { id?: number; title: string; description: string; status: string; priority: string; start_date: string; due_date: string; assignee_id: string; parent_task_id: string; project_id: number; project?: { id: number; name: string }; }
interface Props { task?: Task; project: { id: number; name: string }; taskStatuses: string[]; priorities: string[]; teamMembers: { id: number; name: string }[]; parentTasks: { id: number; title: string }[]; }
const label = (value: string) => value.replace('_', ' ').replace(/^./, c => c.toUpperCase());
export default function TaskForm({ task, project, taskStatuses, priorities, teamMembers, parentTasks }: Props) {
    const isEdit = Boolean(task?.id);
    const { data, setData, post, put, processing, errors } = useForm({ title: task?.title ?? '', description: task?.description ?? '', status: task?.status ?? 'todo', priority: task?.priority ?? 'medium', start_date: task?.start_date ?? '', due_date: task?.due_date ?? '', assignee_id: task?.assignee_id ? String(task.assignee_id) : '', parent_task_id: task?.parent_task_id ? String(task.parent_task_id) : '' });
    const submit = (e: React.FormEvent) => { e.preventDefault(); isEdit ? put('/tasks/' + task!.id) : post('/projects/' + project.id + '/tasks'); };
    const input = 'w-full bg-stone-950 border border-stone-800 text-stone-200 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-amber-500';
    const Field = ({ title, error, children }: { title: string; error?: string; children: React.ReactNode }) => <div><label className="block text-sm font-medium text-stone-300 mb-1">{title}</label>{children}{error && <p className="text-xs text-red-400 mt-1">{error}</p>}</div>;
    return <AppLayout><Head title={isEdit ? 'Edit Task' : 'New Task'} /><div className="p-6 max-w-2xl space-y-6"><div className="flex items-center gap-3"><Link href={'/projects/' + project.id} className="text-stone-500 hover:text-stone-200"><ArrowLeft size={20} /></Link><div><h1 className="text-2xl font-bold text-stone-100">{isEdit ? 'Edit task' : 'New task'}</h1><p className="text-sm text-stone-500 mt-1">Project: {project.name}</p></div></div><form onSubmit={submit} className="bg-stone-900 border border-stone-800 rounded-2xl p-6 space-y-5"><Field title="Task title *" error={errors.title}><input className={input} value={data.title} onChange={e => setData('title', e.target.value)} /></Field><Field title="Description" error={errors.description}><textarea className={input} rows={4} value={data.description} onChange={e => setData('description', e.target.value)} /></Field><div className="grid grid-cols-2 gap-4"><Field title="Status *" error={errors.status}><select className={input} value={data.status} onChange={e => setData('status', e.target.value)}>{taskStatuses.map(s => <option key={s} value={s}>{label(s)}</option>)}</select></Field><Field title="Priority *" error={errors.priority}><select className={input} value={data.priority} onChange={e => setData('priority', e.target.value)}>{priorities.map(p => <option key={p} value={p}>{label(p)}</option>)}</select></Field></div><div className="grid grid-cols-2 gap-4"><Field title="Start date" error={errors.start_date}><input type="date" className={input} value={data.start_date} onChange={e => setData('start_date', e.target.value)} /></Field><Field title="Due date" error={errors.due_date}><input type="date" className={input} value={data.due_date} onChange={e => setData('due_date', e.target.value)} /></Field></div><Field title="Assignee" error={errors.assignee_id}><select className={input} value={data.assignee_id} onChange={e => setData('assignee_id', e.target.value)}><option value="">Unassigned</option>{teamMembers.map(m => <option key={m.id} value={m.id}>{m.name}</option>)}</select></Field><Field title="Parent task" error={errors.parent_task_id}><select className={input} value={data.parent_task_id} onChange={e => setData('parent_task_id', e.target.value)}><option value="">No parent task</option>{parentTasks.map(t => <option key={t.id} value={t.id}>{t.title}</option>)}</select></Field><div className="flex gap-3 pt-2"><button disabled={processing} className="rounded-lg bg-amber-500 px-5 py-2 text-sm font-semibold text-stone-950 hover:bg-amber-400 disabled:opacity-50">{processing ? 'Saving...' : isEdit ? 'Save changes' : 'Create task'}</button><Link href={'/projects/' + project.id} className="rounded-lg border border-stone-700 px-5 py-2 text-sm text-stone-300 hover:bg-stone-800">Cancel</Link></div></form></div></AppLayout>;
}
