import React, { useState } from 'react';
import { Head, Link, router } from '@inertiajs/react';
import AppLayout from '@/components/AppLayout';
import { ArrowLeft, Edit, Trash2, Plus, CheckCircle2, Circle, CalendarDays, UserRound, MoreHorizontal } from 'lucide-react';

interface Task { id: number; title: string; description: string | null; status: string; priority: string; due_date: string | null; completed_at: string | null; assignee: { id: number; name: string } | null; }
interface Project { id: number; name: string; code: string | null; description: string | null; status: string; priority: string; start_date: string | null; due_date: string | null; budget: string | null; currency: string; owner: { id: number; name: string } | null; tasks: Task[]; }
interface Props { project: Project; statuses: string[]; priorities: string[]; taskStatuses: string[]; teamMembers: { id: number; name: string }[]; }
const statusColor: Record<string, string> = { planning: 'bg-blue-100 text-blue-700', active: 'bg-emerald-100 text-emerald-700', on_hold: 'bg-amber-100 text-amber-700', completed: 'bg-purple-100 text-purple-700', archived: 'bg-gray-100 text-gray-600' };
const taskColor: Record<string, string> = { todo: 'bg-gray-100 text-gray-700', in_progress: 'bg-blue-100 text-blue-700', review: 'bg-purple-100 text-purple-700', done: 'bg-emerald-100 text-emerald-700' };
const priorityColor: Record<string, string> = { low: 'text-gray-500', medium: 'text-blue-600', high: 'text-orange-600', urgent: 'text-red-600' };
const label = (value: string) => value.replace('_', ' ').replace(/^./, c => c.toUpperCase());

export default function ProjectShow({ project }: Props) {
    const [filter, setFilter] = useState('all');
    const tasks = filter === 'all' ? project.tasks : project.tasks.filter(t => t.status === filter);
    const done = project.tasks.filter(t => t.status === 'done').length;
    const deleteProject = () => { if (confirm('Delete this project and all its tasks? This cannot be undone.')) router.delete('/projects/' + project.id); };
    const markDone = (task: Task) => { if (!task.completed_at) router.patch('/tasks/' + task.id + '/done'); };

    return <AppLayout><Head title={project.name} /><div className="p-6 max-w-7xl space-y-6">
        <div className="flex items-start justify-between"><div className="flex items-start gap-3"><Link href="/projects" className="mt-1 text-stone-500 hover:text-stone-200"><ArrowLeft size={20} /></Link><div><div className="flex items-center gap-2"><h1 className="text-2xl font-bold text-stone-100">{project.name}</h1>{project.code && <span className="text-sm text-stone-600">{project.code}</span>}</div><div className="flex items-center gap-2 mt-2"><span className={'rounded-full px-2.5 py-1 text-xs font-medium ' + (statusColor[project.status] || '')}>{label(project.status)}</span><span className={'text-xs font-medium ' + (priorityColor[project.priority] || '')}>{label(project.priority)} priority</span></div></div></div><div className="flex gap-2"><Link href={'/projects/' + project.id + '/edit'} className="flex items-center gap-1 rounded-lg border border-stone-700 px-3 py-2 text-sm text-stone-300 hover:bg-stone-800"><Edit size={14} /> Edit</Link><button onClick={deleteProject} className="flex items-center gap-1 rounded-lg border border-red-900/70 px-3 py-2 text-sm text-red-400 hover:bg-red-950/40"><Trash2 size={14} /> Delete</button></div></div>
        <div className="grid grid-cols-4 gap-4"><div className="bg-stone-900 border border-stone-800 rounded-2xl p-4"><div className="text-2xl font-bold text-stone-100">{project.tasks.length}</div><div className="text-xs text-stone-500 mt-1">Total tasks</div></div><div className="bg-stone-900 border border-stone-800 rounded-2xl p-4"><div className="text-2xl font-bold text-emerald-400">{done}</div><div className="text-xs text-stone-500 mt-1">Completed</div></div><div className="bg-stone-900 border border-stone-800 rounded-2xl p-4"><div className="text-2xl font-bold text-amber-400">{project.tasks.length ? Math.round((done / project.tasks.length) * 100) : 0}%</div><div className="text-xs text-stone-500 mt-1">Progress</div></div><div className="bg-stone-900 border border-stone-800 rounded-2xl p-4"><div className="text-lg font-bold text-stone-100">{project.due_date ? new Date(project.due_date).toLocaleDateString('en-KE') : '-'}</div><div className="text-xs text-stone-500 mt-1">Due date</div></div></div>
        <div className="grid lg:grid-cols-3 gap-6"><div className="bg-stone-900 border border-stone-800 rounded-2xl p-5 space-y-4"><h2 className="font-semibold text-stone-100">Project details</h2><p className="text-sm text-stone-400 whitespace-pre-wrap">{project.description || 'No description added.'}</p><div className="space-y-2 text-sm text-stone-400"><div className="flex items-center gap-2"><CalendarDays size={14} /> {project.start_date ? new Date(project.start_date).toLocaleDateString('en-KE') : 'No start date'} – {project.due_date ? new Date(project.due_date).toLocaleDateString('en-KE') : 'No deadline'}</div><div className="flex items-center gap-2"><UserRound size={14} /> {project.owner?.name || 'Unassigned'}</div>{project.budget && <div className="font-medium text-stone-300">{project.currency} {Number(project.budget).toLocaleString()} budget</div>}</div></div>
            <div className="lg:col-span-2 space-y-4"><div className="flex items-center justify-between"><div><h2 className="font-semibold text-stone-100">Tasks</h2><p className="text-xs text-stone-500 mt-1">{done} of {project.tasks.length} completed</p></div><Link href={'/projects/' + project.id + '/tasks/create'} className="inline-flex items-center gap-1 rounded-lg bg-amber-500 px-3 py-2 text-sm font-semibold text-stone-950 hover:bg-amber-400"><Plus size={15} /> Add task</Link></div><div className="flex gap-2 overflow-x-auto pb-1"><button onClick={() => setFilter('all')} className={'px-3 py-1.5 rounded-lg text-xs ' + (filter === 'all' ? 'bg-stone-700 text-stone-100' : 'bg-stone-900 text-stone-500')}>All ({project.tasks.length})</button>{['todo', 'in_progress', 'review', 'done'].map(s => <button key={s} onClick={() => setFilter(s)} className={'px-3 py-1.5 rounded-lg text-xs ' + (filter === s ? 'bg-stone-700 text-stone-100' : 'bg-stone-900 text-stone-500')}>{label(s)} ({project.tasks.filter(t => t.status === s).length})</button>)}</div><div className="bg-stone-900 border border-stone-800 rounded-2xl overflow-hidden">{tasks.length === 0 ? <div className="py-12 text-center text-sm text-stone-500">No tasks in this view.</div> : <div className="divide-y divide-stone-800">{tasks.map(task => <div key={task.id} className="p-4 flex items-start gap-3 hover:bg-stone-850"><button onClick={() => markDone(task)} className="mt-0.5">{task.status === 'done' ? <CheckCircle2 size={18} className="text-emerald-400" /> : <Circle size={18} className="text-stone-600 hover:text-amber-400" />}</button><div className="flex-1 min-w-0"><div className="flex items-center gap-2 flex-wrap"><Link href={'/tasks/' + task.id + '/edit'} className={'text-sm font-medium hover:text-amber-400 ' + (task.status === 'done' ? 'line-through text-stone-600' : 'text-stone-200')}>{task.title}</Link><span className={'rounded-full px-2 py-0.5 text-xs ' + (taskColor[task.status] || '')}>{label(task.status)}</span><span className={'text-xs font-medium ' + (priorityColor[task.priority] || '')}>{label(task.priority)}</span></div>{task.description && <p className="text-xs text-stone-500 mt-1 line-clamp-1">{task.description}</p>}<div className="flex items-center gap-3 mt-2 text-xs text-stone-600">{task.due_date && <span className="flex items-center gap-1"><CalendarDays size={12} /> {new Date(task.due_date).toLocaleDateString('en-KE')}</span>}{task.assignee && <span className="flex items-center gap-1"><UserRound size={12} /> {task.assignee.name}</span>}</div></div><Link href={'/tasks/' + task.id + '/edit'} className="text-stone-600 hover:text-stone-300"><MoreHorizontal size={17} /></Link></div>)}</div>}</div></div></div>
    </div></AppLayout>;
}
